### ISSUE TITLE
Get SMS to E-mail forwarder .apk

### ISSUE THREAD

**Issue by soanvig** [sms-s/Docs#2]
> Get .apk in case app will be removed from google play store

@Maxxer1

**Comment by soanvig** [comment]
@Maxxer1,

Are we using "SMS Forwarder" app?
https://apps.evozi.com/apk-downloader/
This makes downloading .apk possible

**Comment by Maxxer1** [comment]
@soanvig 

App name Missed Call/SMS Mail Forwarder on Play Store

**Comment by Maxxer1** [comment]
Apk backuped on disk and cloud also link to downlad apk on this website http://downloadapk.net/Missed-Call-SMS-Mail-Forwarder.html

**Comment by soanvig** [comment]
We have changed the app to *SMS to Email* by Christian Fees

**Comment by Maxxer1** [comment]
Changed apk on Docs to SMS to Email
